#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir: "/var/lib/vector"

data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686
  playground: false

# Random Syslog-formatted logs
sources:
  prometheus_remote_write:
    type: prometheus_remote_write
    address: 0.0.0.0:19090

  nats-metrics:
    type: "nats_metrics"
    connection_name: nats
    url: nats://localhost:4222
    subject: metrics.>
    queue: queue
    concurrency: 8
    subscriber_capacity: 65536

# Print parsed logs to stdout
sinks:
#  print:
#    type: "console"
#    inputs:
#      - nats-metrics
#    encoding:
#      codec: "json"

  nats_metrics_sink:
    type: "nats_metrics"
    inputs:
      - prometheus_remote_write
    acknowledgements:
      enabled: false
    connection_name: "nats_metrics_sink"
    subject: metrics.{{ tags.cluster }}
    url: nats://localhost:4222
    request:
      concurrency: 64
#    jetstream: true
    batch:
      aggregate: false
      batch_settings:
        max_bytes: 1000000
        max_events: 10000

  prometheus_remote_write_sink:
    endpoint: http://localhost:8428/api/v1/write
    healthcheck:
      enabled: false
    inputs:
      - nats-metrics
    type: prometheus_remote_write
    batch:
      aggregate: false
    default_labels:
      replication: "true"

