#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Change this to use a non-default directory for Vector data storage:
# data_dir: "/var/lib/vector"

# Random Syslog-formatted logs
sources:
  nats-metrics:
    type: "nats_metrics"
    connection_name: nats
    url: nats://localhost
    subject: metrics
    queue: queue
    concurrency: 16
    subscriber_capacity: 65536

transforms:
  metric-aggregate:
    type: aggregate
    inputs:
      - nats-metrics

# Print parsed logs to stdout
sinks:
  print:
    type: "console"
    inputs:
      - nats-metrics
    encoding:
      codec: "json"

  prometheus_remote_write_sink:
    endpoint: http://localhost:8428/api/v1/write
    healthcheck:
      enabled: false
    inputs:
      - nats-metrics
    type: prometheus_remote_write
    batch:
      aggregate: false

